-- =============================================================================
-- SQL Schema for APIx Jevons Index Results Table ('index_values')
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.index_values (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    observation_date DATE NOT NULL,
    base_period_date DATE NOT NULL,
    index_type TEXT NOT NULL CHECK (index_type IN ('elementary', 'route', 'national')),
    route_id TEXT,
    advance_booking_window TEXT,
    index_value NUMERIC(12, 4) NOT NULL,
    num_observations_used INTEGER NOT NULL DEFAULT 0,
    data_provenance_mix JSONB,
    calculated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Performance Indexes for fast dashboard and API queries
CREATE INDEX IF NOT EXISTS idx_index_values_lookup
ON public.index_values (observation_date, index_type, route_id);

CREATE INDEX IF NOT EXISTS idx_index_values_date
ON public.index_values (observation_date DESC);

-- Enable Row Level Security (RLS)
ALTER TABLE public.index_values ENABLE ROW LEVEL SECURITY;

-- Allow public / anon reading
CREATE POLICY "Allow public read access"
ON public.index_values FOR SELECT
USING (true);

-- No INSERT policy: writes go through the privileged DATABASE_URL
-- connection (psycopg2, see jevons_engine_cloud.py's push_to_supabase),
-- which bypasses RLS entirely as the postgres role. Deliberately no
-- anon/authenticated INSERT policy - same pattern as flight_observations/
-- routes/sources, which also have RLS enabled with no policies.
