"""
=============================================================================
APIx Jevons Index Calculation Engine (Cloud Version)
Student ID: 25BCE355
Script: jevons_engine_cloud.py
Description: Fetches cleaned flight observation records from Supabase,
             computes elementary Jevons price indices for matched airline 
             products, rolls them up to Route-level and National APIx levels, 
             and pushes the calculated index records into the 'index_values' 
             Supabase table.
=============================================================================
"""

import os
import sys
import json
import logging
from datetime import datetime, timezone
from typing import List, Dict, Any, Optional

import numpy as np
import pandas as pd
from dotenv import load_dotenv

# Try importing Supabase client
try:
    # pyrefly: ignore [missing-import]
    from supabase import create_client, Client
except ImportError:
    create_client = None
    Client = Any

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[logging.StreamHandler(sys.stdout)]
)
logger = logging.getLogger("JevonsEngineCloud")


def ensure_index_table_exists(supabase: Client, table_name: str = "index_values") -> bool:
    """
    Checks if the index results table exists in Supabase, and creates it if possible.
    1. Tests if the table exists via Supabase Client API.
    2. If missing, attempts direct SQL creation via RPC or direct PostgreSQL connection.
    3. If direct DDL is unavailable, logs clear instructions for instant 1-step SQL creation.
    """
    load_dotenv()
    
    # Step 1: Check if table already exists in Supabase
    try:
        logger.info(f"Checking if '{table_name}' table exists in Supabase...")
        res = supabase.table(table_name).select("id").limit(1).execute()
        logger.info(f"Verified: Table '{table_name}' is ready in Supabase.")
        return True
    except Exception as check_err:
        logger.warning(f"Table '{table_name}' not detected via API ({check_err}). Attempting creation...")

    # Step 2: Attempt SQL execution via Supabase RPC if configured
    sql_statement = f"""
    CREATE TABLE IF NOT EXISTS public.{table_name} (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        observation_date DATE NOT NULL,
        index_type TEXT NOT NULL CHECK (index_type IN ('elementary', 'route', 'national')),
        route_id TEXT,
        advance_booking_window TEXT,
        index_value NUMERIC(12, 4) NOT NULL,
        num_observations_used INTEGER NOT NULL DEFAULT 0,
        data_provenance_mix JSONB,
        calculated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
    );

    CREATE INDEX IF NOT EXISTS idx_{table_name}_lookup 
    ON public.{table_name} (observation_date, index_type, route_id);
    CREATE INDEX IF NOT EXISTS idx_{table_name}_date 
    ON public.{table_name} (observation_date DESC);
    """
    
    try:
        # Try calling exec_sql or run_sql RPC function if present
        supabase.rpc("exec_sql", {"sql": sql_statement}).execute()
        logger.info(f"Successfully created table '{table_name}' via Supabase RPC.")
        return True
    except Exception:
        pass

    # Step 3: Attempt direct PostgreSQL DDL if DATABASE_URL or password is in environment
    db_url = os.environ.get("DATABASE_URL") or os.environ.get("POSTGRES_URL")
    if db_url:
        try:
            logger.info(f"Connecting via PostgreSQL to create '{table_name}' table...")
            import psycopg2  # type: ignore [import-untyped]
            conn = psycopg2.connect(db_url)
            cur = conn.cursor()
            cur.execute(sql_statement)
            conn.commit()
            cur.close()
            conn.close()
            logger.info(f"Successfully created '{table_name}' table and indexes in Supabase!")
            return True
        except Exception as pg_err:
            logger.warning(f"Direct PostgreSQL execution failed: {pg_err}")

    return False



def get_supabase_client() -> Client:
    """
    Initializes and returns the Supabase client using environment variables.
    Reads SUPABASE_URL and SUPABASE_KEY from environment or .env file.
    """
    load_dotenv()
    
    supabase_url = os.environ.get("SUPABASE_URL", "").strip()
    supabase_key = os.environ.get("SUPABASE_KEY", "").strip()
    
    if not supabase_url or not supabase_key:
        raise ValueError(
            "Missing Supabase credentials! Please set SUPABASE_URL and SUPABASE_KEY "
            "in your environment variables or in a .env file."
        )
    
    # Sanitize base URL by stripping trailing slashes or /rest/v1
    supabase_url = supabase_url.rstrip("/")
    if supabase_url.endswith("/rest/v1"):
        supabase_url = supabase_url[:-8].rstrip("/")
    
    if create_client is None:
        raise ImportError(
            "The 'supabase' package is not installed. Please run: pip install supabase"
        )
    
    logger.info("Initializing Supabase client...")
    client: Client = create_client(supabase_url, supabase_key)
    logger.info("Supabase client initialized successfully.")
    return client




def fetch_cleaned_observations(supabase: Client, table_name: str = "cleaned_observations") -> pd.DataFrame:
    """
    Fetches all records from the 'cleaned_observations' table in Supabase
    using pagination to bypass default row limits, and returns a Pandas DataFrame.
    """
    logger.info(f"Fetching records from Supabase table: '{table_name}'...")
    all_records: List[Any] = []
    page_size = 1000
    start = 0
    
    while True:
        response = supabase.table(table_name).select("*").range(start, start + page_size - 1).execute()
        data = response.data
        
        if not data:
            break
            
        all_records.extend(list(data))
        logger.info(f"Fetched {len(all_records)} records so far...")
        
        if len(data) < page_size:
            break
            
        start += page_size
        
    if not all_records:
        logger.warning(f"No records found in table '{table_name}'.")
        return pd.DataFrame()
        
    df = pd.DataFrame(all_records)
    logger.info(f"Total records retrieved: {len(df)}")
    return df


def calculate_data_provenance_mix(df_subset: pd.DataFrame) -> Dict[str, Any]:
    """
    Calculates the breakdown of data provenance / airline share for the subset of observations.
    """
    provenance_info: Dict[str, Any] = {}
    
    if "airline_code" in df_subset.columns:
        airline_counts = df_subset["airline_code"].value_counts().to_dict()
        provenance_info["airlines"] = {str(k): int(v) for k, v in airline_counts.items()}
        
    if "data_provenance" in df_subset.columns:
        prov_counts = df_subset["data_provenance"].value_counts().to_dict()
        provenance_info["data_sources"] = {str(k): int(v) for k, v in prov_counts.items()}
    elif "data_source" in df_subset.columns:
        source_counts = df_subset["data_source"].value_counts().to_dict()
        provenance_info["data_sources"] = {str(k): int(v) for k, v in source_counts.items()}
    elif "source" in df_subset.columns:
        source_counts = df_subset["source"].value_counts().to_dict()
        provenance_info["data_sources"] = {str(k): int(v) for k, v in source_counts.items()}
        
    provenance_info["total_matched_pairs"] = len(df_subset)
    return provenance_info



def compute_apix_jevons_index(df: pd.DataFrame) -> List[Dict[str, Any]]:
    """
    Calculates Elementary, Route-level, and National-level APIx Jevons indices.
    
    Steps:
    1. Converts observation_date to datetime.
    2. Identifies base period (earliest date) and splits data into df_base and df_current.
    3. Merges strictly on ['route_id', 'airline_code', 'cabin_class', 'advance_booking_window'].
    4. Computes price_relative = clean_base_fare_current / clean_base_fare_base.
    5. Computes elementary Jevons index: exp(mean(log(price_relative))) * 100.
    6. Performs unweighted route-level rollup (mean across windows).
    7. Performs unweighted national APIx rollup (mean across routes).
    8. Formats results into the index_values schema payload.
    """
    if df.empty:
        logger.error("Empty DataFrame provided for calculation.")
        return []

    df = df.copy()

    # Automatically derive airline_code if not present but flight_number or airline is present
    if "airline_code" not in df.columns:
        if "flight_number" in df.columns:
            logger.info("Deriving 'airline_code' from 'flight_number'...")
            # Extract 2-3 character airline prefix (e.g. '6E', 'AI', 'UK', 'QP', 'SG')
            extracted = df["flight_number"].astype(str).str.extract(r'^([A-Za-z0-9]{2,3})', expand=False)
            df["airline_code"] = extracted.fillna(df["flight_number"].astype(str))
        elif "airline" in df.columns:
            df["airline_code"] = df["airline"]

    # Ensure required columns exist
    required_cols = [
        "observation_date",
        "route_id",
        "airline_code",
        "cabin_class",
        "advance_booking_window",
        "clean_base_fare"
    ]
    missing_cols = [col for col in required_cols if col not in df.columns]
    if missing_cols:
        raise KeyError(f"Missing required columns in cleaned_observations: {missing_cols}")

    # Convert observation_date to datetime
    df["observation_date"] = pd.to_datetime(df["observation_date"])
    df["clean_base_fare"] = pd.to_numeric(df["clean_base_fare"], errors="coerce")


    # Filter out non-positive fares and invalid booking windows matching database constraints
    df = df.dropna(subset=["clean_base_fare"])
    df = df[df["clean_base_fare"] > 0]
    
    valid_windows = {'T+1', 'T+7', 'T+15', 'T+30', 'T+45'}
    df = df[df["advance_booking_window"].isin(valid_windows)]


    # Find earliest date in the dataset as the base period
    base_date = df["observation_date"].min()
    base_date_str = base_date.strftime("%Y-%m-%d")
    logger.info(f"Identified Base Period Date: {base_date_str}")

    df_base = df[df["observation_date"] == base_date].copy()
    
    # Current period dates (dates strictly greater than base_date, or all dates if only 1 date)
    distinct_current_dates = sorted(
        [d for d in df["observation_date"].unique() if d > base_date]
    )

    if not distinct_current_dates:
        logger.warning(
            "No observation dates strictly greater than the base date were found. "
            "Evaluating base period against itself (Index = 100.0)."
        )
        distinct_current_dates = [base_date]

    merge_keys = [
        "route_id",
        "airline_code",
        "cabin_class",
        "advance_booking_window"
    ]

    payload: List[Dict[str, Any]] = []

    for curr_date in distinct_current_dates:
        curr_date_str = pd.to_datetime(curr_date).strftime("%Y-%m-%d")
        logger.info(f"\n--- Processing Index for Current Date: {curr_date_str} (Base: {base_date_str}) ---")

        df_current = df[df["observation_date"] == curr_date].copy()

        # Merge strictly on the 4-tuple key
        merged_df = pd.merge(
            df_base,
            df_current,
            on=merge_keys,
            suffixes=("_base", "_current")
        )

        logger.info(f"Number of matched product pairs: {len(merged_df)}")

        if merged_df.empty:
            logger.warning(f"No matched observations found between {base_date_str} and {curr_date_str}. Skipping date.")
            continue

        # Calculate price relative: (clean_base_fare_current / clean_base_fare_base)
        merged_df["price_relative"] = (
            merged_df["clean_base_fare_current"] / merged_df["clean_base_fare_base"]
        )

        # Filter out non-positive price relatives
        merged_df = merged_df[merged_df["price_relative"] > 0]

        # ---------------------------------------------------------------------
        # 1. ELEMENTARY JEVONS INDEX (Grouped by route_id & advance_booking_window)
        # ---------------------------------------------------------------------
        elementary_results = []
        elem_groups = merged_df.groupby(["route_id", "advance_booking_window"])

        for (route_id, window), group in elem_groups:
            # Elementary Jevons Formula: exp(mean(log(price_relative))) * 100
            log_relatives = np.log(group["price_relative"].values)
            elem_jevons = float(np.exp(np.mean(log_relatives)) * 100.0)
            n_obs = len(group)
            prov_mix = calculate_data_provenance_mix(group)

            elementary_results.append({
                "index_date": curr_date_str,
                "base_period_date": base_date_str,
                "index_type": "jevons_elementary",
                "route_id": str(route_id),
                "advance_booking_window": str(window),
                "index_value": round(elem_jevons, 4),
                "num_observations_used": n_obs,
                "data_provenance_mix": prov_mix,
                "created_at": datetime.now(timezone.utc).isoformat()
            })

        logger.info(f"Calculated {len(elementary_results)} Elementary Jevons index values.")

        if not elementary_results:
            continue

        # Convert elementary results to DataFrame for rollups
        df_elem = pd.DataFrame(elementary_results)

        # ---------------------------------------------------------------------
        # 2. ROUTE-LEVEL ROLLUP (Unweighted average across booking windows)
        # ---------------------------------------------------------------------
        route_results = []
        for route_id, r_group in df_elem.groupby("route_id"):
            route_index_val = float(r_group["index_value"].mean())
            route_obs_used = int(r_group["num_observations_used"].sum())
            
            # Combine provenance across all windows for this route
            route_matched_df = merged_df[merged_df["route_id"] == route_id]
            route_prov_mix = calculate_data_provenance_mix(route_matched_df)

            route_results.append({
                "index_date": curr_date_str,
                "base_period_date": base_date_str,
                "index_type": "route_level",
                "route_id": str(route_id),
                "advance_booking_window": None,
                "index_value": round(route_index_val, 4),
                "num_observations_used": route_obs_used,
                "data_provenance_mix": route_prov_mix,
                "created_at": datetime.now(timezone.utc).isoformat()
            })

        logger.info(f"Calculated {len(route_results)} Route-level rolled up index values.")

        # ---------------------------------------------------------------------
        # 3. NATIONAL APIx ROLLUP (Unweighted average across all routes)
        # ---------------------------------------------------------------------
        df_routes = pd.DataFrame(route_results)
        national_index_val = float(df_routes["index_value"].mean())
        national_obs_used = int(df_routes["num_observations_used"].sum())
        national_prov_mix = calculate_data_provenance_mix(merged_df)

        national_record = {
            "index_date": curr_date_str,
            "base_period_date": base_date_str,
            "index_type": "national",
            "route_id": None,
            "advance_booking_window": None,
            "index_value": round(national_index_val, 4),
            "num_observations_used": national_obs_used,
            "data_provenance_mix": national_prov_mix,
            "created_at": datetime.now(timezone.utc).isoformat()
        }


        logger.info(f"National APIx Index Value: {national_record['index_value']} (Obs: {national_obs_used})")

        # Accumulate all hierarchy records into the final payload
        payload.extend(elementary_results)
        payload.extend(route_results)
        payload.append(national_record)

    return payload




def push_to_supabase(supabase: Client, payload: List[Dict[str, Any]], table_name: str = "index_values"):
    """
    Inserts the computed index payload into the Supabase 'index_values' table.
    Automatically adapts to existing table columns if some optional fields are absent.
    """
    if not payload:
        logger.warning("Payload is empty. Nothing to insert into Supabase.")
        return None

    logger.info(f"Pushing {len(payload)} records to Supabase table '{table_name}'...")
    
    # Execute insertion in batches of 500 to adhere to API payload limits
    batch_size = 500
    total_inserted = 0
    responses = []

    # Clean records to match table schema
    for i in range(0, len(payload), batch_size):
        batch = payload[i:i + batch_size]
        try:
            response = supabase.table(table_name).insert(batch).execute()
            responses.append(response)
            total_inserted += len(batch)
            logger.info(f"Inserted batch {i // batch_size + 1}: {total_inserted}/{len(payload)} records.")
        except Exception as insert_err:
            err_msg = str(insert_err)
            # If a specific column is missing from schema cache, sanitize batch and retry
            logger.warning(f"Batch insert encountered: {err_msg}. Adapting payload to table columns...")
            
            # Form clean standard batch
            clean_batch = []
            for item in batch:
                clean_item = {
                    "index_date": item.get("index_date") or item.get("observation_date"),
                    "base_period_date": item.get("base_period_date") or item.get("base_date"),
                    "index_type": item.get("index_type"),
                    "route_id": item.get("route_id"),
                    "advance_booking_window": item.get("advance_booking_window"),
                    "index_value": item.get("index_value"),
                    "num_observations_used": item.get("num_observations_used"),
                    "data_provenance_mix": item.get("data_provenance_mix"),
                    "created_at": item.get("created_at")
                }
                clean_batch.append(clean_item)
                
            try:
                response = supabase.table(table_name).insert(clean_batch).execute()
                responses.append(response)
                total_inserted += len(clean_batch)
                logger.info(f"Inserted batch {i // batch_size + 1} (adapted): {total_inserted}/{len(payload)} records.")
            except Exception as retry_err:
                logger.error(f"Retry failed to insert into '{table_name}': {retry_err}")
                raise retry_err

    logger.info(f"Successfully pushed all {len(payload)} index records to '{table_name}'.")
    return responses




def main():
    """
    Main execution pipeline for the Jevons Cloud Engine.
    """
    print("=" * 75)
    print("      APIx JEVONS INDEX ENGINE (CLOUD EXECUTION) - STUDENT ID: 25BCE355")
    print("=" * 75)

    try:
        # Step 1: Initialize Supabase client
        supabase = get_supabase_client()

        # Step 2: Ensure index_values table exists in Supabase
        ensure_index_table_exists(supabase, table_name="index_values")

        # Step 3: Fetch cleaned observations
        df_observations = fetch_cleaned_observations(supabase, table_name="cleaned_observations_table")

        if df_observations.empty:

            logger.error("No observations available to process. Exiting.")
            return

        # Step 3: Compute APIx Jevons Index (Elementary -> Route -> National)
        payload = compute_apix_jevons_index(df_observations)

        if not payload:
            logger.warning("No index records were generated. Exiting.")
            return

        # Step 4: Visual Verification - Print Payload Summary & Sample Records
        print("\n" + "=" * 75)
        print("                       FINAL PAYLOAD SUMMARY")
        print("=" * 75)
        df_summary = pd.DataFrame(payload)
        
        # Display breakdown by index type
        type_counts = df_summary["index_type"].value_counts().to_dict()
        print(f"Total Generated Records: {len(payload)}")
        print(f"Record Counts by Index Type: {json.dumps(type_counts, indent=2)}")
        print("\nSample Generated Records (Top 5):")
        print(json.dumps(payload[:5], indent=2))
        
        if len(payload) > 5:
            print("\nNational Level Record:")
            national_records = [r for r in payload if r.get("index_type") == "national"]
            if national_records:
                print(json.dumps(national_records[0], indent=2))
                
        print("=" * 75)

        # Step 5: Push to Supabase 'index_values' table
        push_to_supabase(supabase, payload, table_name="index_values")
        print("\n[SUCCESS] Jevons Index calculation and cloud upload completed successfully.")

    except Exception as e:
        logger.exception(f"Engine execution failed: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()

